version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Oslo"
    assignees:
    - espenhermansen
    reviewers:
    - espenhermansen
    open-pull-requests-limit: 10
